### ISSUE TITLE
Any plan on releasing the dataset and training code?

### ISSUE THREAD

**Issue by hyer** [posterllava/PosterLLaVA#2]
Hi, this work is interesting. Whether there is a point in time to release the dataset and the code.

**Comment by XinAn9508** [comment]
+1

**Comment by YooGunWook** [comment]
+1

**Comment by dydxdt** [comment]
+1

**Comment by chenyanyin** [comment]
+1

**Comment by posterllava** [comment]
we've released the training code and dataset. glad to see it is useful.

**Comment by shin-wn** [comment]
Thanks for your great work!
Do you have a plan to release the code for inpainting and saliency detection?

Looking forward your reply !!

**Comment by zimenglan-sysu-512** [comment]
any update?

**Comment by posterllava** [comment]
> Thanks for your great work! Do you have a plan to release the code for inpainting and saliency detection?
> 
> Looking forward your reply !!

We here mention again the methods used for inpainting and saliency detection in our paper, which are **lama** [https://github.com/saic-mdal/lama ](URL) and **basenet** [https://github.com/xuebinqin/BASNet](url). 

Hope the official script can solve your problem!

**Comment by HappyNotHappy** [comment]
> > Thanks for your great work! Do you have a plan to release the code for inpainting and saliency detection?
> > Looking forward your reply !!
> 
> We here mention again the methods used for inpainting and saliency detection in our paper, which are **lama** [https://github.com/saic-mdal/lama ](URL) and **basenet** [https://github.com/xuebinqin/BASNet](url).
> 
> Hope the official script can solve your problem!


The environment of lama is extremely hard to build, take tons of time still not working, could you please kindly release inpainting data of qbposter ?
